#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NBP_Neo4j_Redis.Resource", IsApplication=true)]

namespace NBP_Neo4j_Redis
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Fab.Resource.Attribute.fab_colorDisabled = global::NBP_Neo4j_Redis.Resource.Attribute.fab_colorDisabled;
			global::Refractored.Fab.Resource.Attribute.fab_colorNormal = global::NBP_Neo4j_Redis.Resource.Attribute.fab_colorNormal;
			global::Refractored.Fab.Resource.Attribute.fab_colorPressed = global::NBP_Neo4j_Redis.Resource.Attribute.fab_colorPressed;
			global::Refractored.Fab.Resource.Attribute.fab_colorRipple = global::NBP_Neo4j_Redis.Resource.Attribute.fab_colorRipple;
			global::Refractored.Fab.Resource.Attribute.fab_shadow = global::NBP_Neo4j_Redis.Resource.Attribute.fab_shadow;
			global::Refractored.Fab.Resource.Attribute.fab_size = global::NBP_Neo4j_Redis.Resource.Attribute.fab_size;
			global::Refractored.Fab.Resource.Attribute.layoutManager = global::NBP_Neo4j_Redis.Resource.Attribute.layoutManager;
			global::Refractored.Fab.Resource.Attribute.reverseLayout = global::NBP_Neo4j_Redis.Resource.Attribute.reverseLayout;
			global::Refractored.Fab.Resource.Attribute.spanCount = global::NBP_Neo4j_Redis.Resource.Attribute.spanCount;
			global::Refractored.Fab.Resource.Attribute.stackFromEnd = global::NBP_Neo4j_Redis.Resource.Attribute.stackFromEnd;
			global::Refractored.Fab.Resource.Color.fab_material_blue_500 = global::NBP_Neo4j_Redis.Resource.Color.fab_material_blue_500;
			global::Refractored.Fab.Resource.Dimension.fab_elevation_lollipop = global::NBP_Neo4j_Redis.Resource.Dimension.fab_elevation_lollipop;
			global::Refractored.Fab.Resource.Dimension.fab_scroll_threshold = global::NBP_Neo4j_Redis.Resource.Dimension.fab_scroll_threshold;
			global::Refractored.Fab.Resource.Dimension.fab_shadow_size = global::NBP_Neo4j_Redis.Resource.Dimension.fab_shadow_size;
			global::Refractored.Fab.Resource.Dimension.fab_size_mini = global::NBP_Neo4j_Redis.Resource.Dimension.fab_size_mini;
			global::Refractored.Fab.Resource.Dimension.fab_size_normal = global::NBP_Neo4j_Redis.Resource.Dimension.fab_size_normal;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::NBP_Neo4j_Redis.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::NBP_Neo4j_Redis.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::Refractored.Fab.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::NBP_Neo4j_Redis.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::Refractored.Fab.Resource.Drawable.fab_shadow = global::NBP_Neo4j_Redis.Resource.Drawable.fab_shadow;
			global::Refractored.Fab.Resource.Drawable.fab_shadow_mini = global::NBP_Neo4j_Redis.Resource.Drawable.fab_shadow_mini;
			global::Refractored.Fab.Resource.Id.item_touch_helper_previous_elevation = global::NBP_Neo4j_Redis.Resource.Id.item_touch_helper_previous_elevation;
			global::Refractored.Fab.Resource.Id.mini = global::NBP_Neo4j_Redis.Resource.Id.mini;
			global::Refractored.Fab.Resource.Id.normal = global::NBP_Neo4j_Redis.Resource.Id.normal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::Refractored.Fab.Resource.Styleable.FloatingActionButton_fab_size = global::NBP_Neo4j_Redis.Resource.Styleable.FloatingActionButton_fab_size;
			global::Refractored.Fab.Resource.Styleable.RecyclerView = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_descendantFocusability = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_android_orientation = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_android_orientation;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_layoutManager = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_layoutManager;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_reverseLayout = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_reverseLayout;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_spanCount = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_spanCount;
			global::Refractored.Fab.Resource.Styleable.RecyclerView_stackFromEnd = global::NBP_Neo4j_Redis.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int fab_colorDisabled = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int fab_colorNormal = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int fab_colorPressed = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int fab_colorRipple = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int fab_shadow = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fab_size = 2130771987;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int layout_aspectRatio = 2130771981;
			
			// aapt resource value: 0x7f010005
			public const int layout_heightPercent = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public const int layout_marginBottomPercent = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int layout_marginEndPercent = 2130771980;
			
			// aapt resource value: 0x7f010007
			public const int layout_marginLeftPercent = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int layout_marginPercent = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int layout_marginRightPercent = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int layout_marginStartPercent = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int layout_marginTopPercent = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int layout_widthPercent = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int fab_material_blue_500 = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int fab_elevation_lollipop = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int fab_scroll_threshold = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int fab_shadow_size = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_size_mini = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_size_normal = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dugme = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fab_shadow_mini = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_send = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Mladen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rotate100 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int user = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int PprofilnaSlika = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int btnLogIn = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btnSignIn = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int containerLoga = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int containerProfilne = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int containerRotacije = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int editTextDatumRodjenja = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int editTextIme = 2131034134;
			
			// aapt resource value: 0x7f05000b
			public const int editTextKorisnicko = 2131034123;
			
			// aapt resource value: 0x7f050019
			public const int editTextMestoStanovanja = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int editTextPassword = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int editTextPol = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int editTextPrezime = 2131034135;
			
			// aapt resource value: 0x7f05000c
			public const int editTextSifra = 2131034124;
			
			// aapt resource value: 0x7f05001b
			public const int editTextUsername = 2131034139;
			
			// aapt resource value: 0x7f050003
			public const int fab = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int input = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int itemKamera = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int itemOdaberi = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int ivRotacija = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int list_of_messages = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int message_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int message_time = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int message_user = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int profilnaSlika = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int slikaLogo = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int List_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PopUpProfilnaSlikaMenu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profile = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SignIn = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] PercentLayout_Layout = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
